### ISSUE TITLE
Broken HTTPS

### ISSUE THREAD

**Issue by johnkramorbhz** [MinxiangPan/UBPlatform#23]
If I do not allow Google Chrome to load unsafe contents on your deployed website, searching is broken and unusable. 
After a look through the debug interface on Google Chrome, I found out that you used the resource on `3.18.110.2:3001`. Please consider fixing that problem.
In addition, please make the access of your deployed project easier by telling us the entry point.

**Comment by MinxiangPan** [comment]
working on the server side to support https.

**Comment by MinxiangPan** [comment]
Server Side now got SSL on its own and I update the website to https. Currently, the website and server both support https connection.
